---
abstract: 'CRUD tasks for fimfiction.net'
author:
  - 'Cameron Thornton <cthor@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Fimfiction
no_index:
  directory:
    - inc
    - t
recommends:
  JSON::XS: 0
requires:
  Carp: 0
  HTML::TreeBuilder: 0
  HTTP::Cookies: 0
  JSON: 0
  LWP::UserAgent: 0
  XML::Twig: 0
  perl: 5.14.0
resources:
  license: http://dev.perl.org/licenses/
version: v0.3.7
